# Generated by Django 3.2.9 on 2021-11-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211017_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito_detalle',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
