# Generated by Django 3.2.9 on 2021-11-06 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_carrito_detalle_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='id_usuario',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
